In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [4]:
df = pd.read_csv('Car_Purchasing_Data.csv')
df

,Gender,Age,Annual Salary,Credit Card Debt,Net Worth,Car Purchase Amount
0,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248
...,...,...,...,...,...,...
495,0,41.462515,71942.40291,6995.902524,541670.1016,48901.44342
496,1,37.642000,56039.49793,12301.456790,360419.0988,31491.41457
497,1,53.943497,68888.77805,10611.606860,764531.3203,64147.28888
498,1,59.160509,49811.99062,14013.034510,337826.6382,45442.15353
499,1,46.731152,61370.67766,9391.341628,462946.4924,45107.22566

In [5]:
len(df)

500

In [6]:
df.shape

(500, 6)

In [7]:
df.size

3000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Gender               500 non-null    int64
 1   Age                  500 non-null    float64
 2   Annual Salary        500 non-null    float64
 3   Credit Card Debt     500 non-null    float64
 4   Net Worth            500 non-null    float64
 5   Car Purchase Amount  500 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 23.6 KB

In [9]:
#Performing MUltiple Linear Regression

X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [10]:
X

     Gender        Age  Annual Salary  Credit Card Debt    Net Worth
0         0  41.851720    62812.09301      11609.380910  238961.2505
1         0  40.870623    66646.89292       9572.957136  530973.9078
2         1  43.152897    53798.55112      11160.355060  638467.1773
3         1  58.271369    79370.03798      14426.164850  548599.0524
4         1  57.313749    59729.15130       5358.712177  560304.0671
..      ...        ...            ...               ...          ...
495       0  41.462515    71942.40291       6995.902524  541670.1016
496       1  37.642000    56039.49793      12301.456790  360419.0988
497       1  53.943497    68888.77805      10611.606860  764531.3203
498       1  59.160509    49811.99062      14013.034510  337826.6382
499       1  46.731152    61370.67766       9391.341628  462946.4924

[500 rows x 5 columns]

In [11]:
y

0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: Car Purchase Amount, Length: 500, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
len(X_train) , len(y_train)

(350, 350)

In [14]:
len(X_test) , len(y_test)

(150, 150)

In [15]:
X_train

     Gender        Age  Annual Salary  Credit Card Debt    Net Worth
5         1  56.824893    68499.85162      14179.472440  428485.3604
116       1  43.031069    69175.19403       6039.594519  325701.4083
45        0  55.275143    70787.27764      10155.340950  853913.8532
16        0  44.742200    63259.87837      11495.549990  370356.2223
462       0  39.141035    66680.27410      10263.148990  556945.8742
..      ...        ...            ...               ...          ...
106       0  41.796014    51075.46118      12416.848450  450402.2932
270       0  35.375156    33422.99683       8570.611562  211168.6293
348       0  45.305941    63561.04525       3730.119720  608019.6308
435       1  57.974293    41409.29390       8211.340920  421318.9764
102       1  30.492353    68289.18229       7357.787011  404457.3099

[350 rows x 5 columns]

In [16]:
y_train

5      56611.99784
116    42408.02625
45     68925.09447
16     41814.72067
462    44430.63323
          ...
106    34803.82395
270    12536.93842
348    49348.88394
435    42139.64528
102    33640.73697
Name: Car Purchase Amount, Length: 350, dtype: float64

In [17]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [18]:
reg.coef_

array([-5.99401193e-02,  8.41564679e+02,  5.62334352e-01, -2.90660624e-05,
        2.89836840e-02])

In [19]:
reg.intercept_

-42147.25929316858

In [20]:
-5.99401193e-02*1	 + 8.41564679e+02*56.824893+ 5.62334352e-01*68499.85162+ -2.90660624e-05*14179.472440 + 2.89836840e-02*428485.3604 + -42147.25929316858

56612.99541932429

In [21]:
#Training_data Performance


y_train_pred = reg.predict(X_train)
y_train_pred

array([56612.9954996 , 42405.54760383, 68925.74034943, 41813.35176029,
       44431.10711999, 39269.96796049, 67424.30820745, 56562.50572671,
       45113.79446678, 37349.28309601, 49139.07525807, 39607.72351574,
       48515.36454392, 43991.80150333, 34921.39509945, 48052.95055006,
       37161.84813267, 47434.88210007,  9001.51793095, 27589.64957169,
       10091.80387451, 38170.90657229, 59538.6201211 , 42591.98024911,
       30241.69441766, 49050.03801569, 56765.56404033, 39331.28587765,
       53658.01986332, 29757.51531894, 53993.87323184, 50456.14633048,
       63869.85737968, 38707.0704675 , 46013.11332846, 29425.09315133,
       48956.05567373, 43680.35227086, 55126.09944117, 36110.72469181,
       47761.79417663, 55701.42483024, 70597.29015939, 52709.15668229,
       54974.51265591, 31215.0246528 , 45974.97774087, 25973.00354464,
       42355.55928967, 46713.96353216, 27588.712329  , 42383.73695527,
       34137.74363623, 40876.81978467, 55593.40654571, 46188.67543173,
       51356.29488468, 52993.58512978, 36518.07113458, 54605.77581037,
       56973.71419897, 34518.87087397, 51868.31518195, 63036.41824876,
       29093.54466646, 46936.05786138, 22599.39403976, 27626.40692133,
       42794.46310494, 42990.6120113 , 60567.02630902, 52118.3327811 ,
       38977.51251838, 49721.84190501, 32701.68627656, 49064.02964428,
       52311.69827426, 39132.78767993, 41574.12332733, 32737.80681953,
       58839.62146123, 12895.01663889, 50540.33271171, 28924.14810267,
       47985.15852102, 32291.94840348, 39424.30465127, 39433.69647091,
       27808.93888463, 64545.24007023, 41678.92637001, 54387.42206414,
       27301.0568974 , 59045.93301418, 47716.11443182, 31542.93312161,
       41458.93162757, 35929.36797872, 42866.22842451, 35440.66878388,
       28166.13002021, 38146.60018899, 35138.31845694, 49219.3357053 ,
       42747.86437817, 30734.87692955, 38505.31577564, 43642.57353355,
       47935.48148244, 42909.57268961, 46413.31100199, 51402.42872527,
       52888.26886373, 61594.41315994, 36644.41378807, 44437.14915364,
       42703.71773595, 39503.94205337, 19525.1258344 , 59416.30843059,
       58045.0463158 , 40659.90556458, 60762.80519476, 40020.3590171 ,
       29670.24875776, 44426.14868708, 35851.87403641, 30760.72988606,
       57460.21966441, 47143.16276179, 44464.25318478, 56457.81151595,
       38175.19117008, 41674.50527112, 44002.43007022, 62029.10095964,
       70879.61716304, 28645.67440742, 36367.0533542 , 53848.81274897,
       58668.51058659, 46937.33803747, 65594.64434947, 23519.41447594,
       57306.85359318, 30721.07628167, 49440.01084415, 35473.26407318,
       32555.5311289 , 21472.04039055, 40092.93871385, 58235.0689183 ,
       35716.65719082, 42481.38070376, 47695.34761802, 31696.73257144,
       41326.3425173 , 46054.99882616, 67119.65203565, 42214.97546576,
       41429.93356848, 45508.0533885 , 38140.09263666, 37869.64597715,
       37251.4585768 , 50442.50213244, 46401.28939091, 34642.89697474,
       60958.9727316 , 53497.84739287, 40076.31769814, 45272.41543195,
       68678.62353625, 29558.01359352, 52952.90378413, 29415.11654654,
       19552.39173013, 56497.9319264 , 39521.55882008, 36126.85812718,
       37714.36204335, 28699.74742464, 51610.66126396, 58351.83043268,
       41027.6851713 , 44419.04523263, 42920.1452278 , 59095.31048789,
       37304.06961263, 40003.57574413, 63738.20382121, 46324.48131235,
       56510.57728551, 50296.43153358, 29048.94639643, 41565.68135191,
       45442.12190614, 48465.22709848, 45805.5697126 , 32829.40799655,
       43401.44438911, 37376.47341532, 55913.18175866, 48348.24192059,
       49247.37931924, 57442.31721595, 46390.17391225, 45593.63274318,
       44577.18589467, 27887.68235269, 52473.22102707, 39905.90627928,
       47806.43073861, 47482.2335956 , 37843.85920026, 66363.03660631,
       37949.959924  , 43504.12078989, 36086.1748145 , 66645.05190708,
       49093.26064435, 31410.3362734 , 52656.31053368, 51405.38941948,
       47609.54022384, 43856.16431409, 47720.26360028, 33425.52146132,
       49729.71448801, 48620.26089441, 52665.67318142, 48382.24466838,
       48011.85067011, 36545.94393645, 51049.36084486, 42297.02653282,
       63253.01103689, 49510.62180665, 26502.16689625, 45804.13438739,
       37257.48719078, 47980.02320421, 30420.98052738, 44846.03732439,
       41030.58159524, 55420.17989412, 32061.07378824, 30826.03688996,
       47009.87642749, 54849.56828087, 43408.52849372, 28439.87466231,
       45823.87570616, 24182.8065439 , 41987.10884485, 41490.6123269 ,
       67092.45443285, 24221.94584582, 66890.3575023 , 43264.8121834 ,
       46452.24349338, 27816.84521753, 46643.46088969, 43241.85310537,
       56584.28897097, 37082.48654392, 49336.6695324 , 45736.18527528,
       46381.24963701, 26598.84003606, 45115.1527517 , 24133.5305772 ,
       45014.85492811, 48734.8369472 , 40590.75054187, 38400.32705245,
       48516.47813514, 39810.46856305, 48303.24209643, 42907.87758139,
       37181.81165914, 51223.83362542, 34677.17366087, 44500.27570284,
       48265.78973678, 46400.98855866, 54014.9183927 , 46848.00266086,
       49257.85324291, 79998.38224614, 50933.79805913, 42703.38821522,
       53501.49496254, 20654.78738564, 31146.65182362, 60117.48614542,
       33130.32175709, 56067.17842943, 53048.03508566, 58642.57439076,
       42776.50958243, 31979.7987354 , 35727.89194054, 27188.01980393,
       48785.60007105, 41103.66941756, 52151.30605355, 46379.92509884,
       31489.70866942, 42977.08177484, 38182.93626789, 38146.99489258,
       37885.29602121, 35659.86634191, 50705.83149539, 49080.30524024,
       43405.06254077, 35777.82892574, 35457.06591642, 57124.86401286,
       48024.91138373, 38900.02051724, 42774.37822191, 51922.57252917,
       44735.04056578, 33763.3260387 , 50188.50964674, 33259.84017619,
       42499.8826183 , 38929.42552674, 51552.17093032, 47604.57221301,
       39083.54678692, 42186.62773742, 38546.96310281, 36018.44575105,
       40103.46629187, 31087.32542657, 37742.17709866, 28464.96427039,
       41914.64793135, 45108.43018434, 51131.32149183, 60867.02860699,
       49372.6706871 , 34802.23265009, 12538.31785211, 49345.72029335,
       42138.80389105, 33637.77040989])

In [22]:
Training_data_Performance = pd.DataFrame()
Training_data_Performance = X_train.copy()
Training_data_Performance['Actual_y_train'] = y_train.copy()
Training_data_Performance['y_train_pred'] = y_train_pred


Training_data_Performance

,Gender,Age,Annual Salary,Credit Card Debt,Net Worth,Actual_y_train,y_train_pred
5,1,56.824893,68499.85162,14179.472440,428485.3604,56611.99784,56612.995500
116,1,43.031069,69175.19403,6039.594519,325701.4083,42408.02625,42405.547604
45,0,55.275143,70787.27764,10155.340950,853913.8532,68925.09447,68925.740349
16,0,44.742200,63259.87837,11495.549990,370356.2223,41814.72067,41813.351760
462,0,39.141035,66680.27410,10263.148990,556945.8742,44430.63323,44431.107120
...,...,...,...,...,...,...,...
106,0,41.796014,51075.46118,12416.848450,450402.2932,34803.82395,34802.232650
270,0,35.375156,33422.99683,8570.611562,211168.6293,12536.93842,12538.317852
348,0,45.305941,63561.04525,3730.119720,608019.6308,49348.88394,49345.720293
435,1,57.974293,41409.29390,8211.340920,421318.9764,42139.64528,42138.803891
102,1,30.492353,68289.18229,7357.787011,404457.3099,33640.73697,33637.770410

In [23]:
Training_data_Performance.index

Index([  5, 116,  45,  16, 462, 357,   3, 218, 405,  60,
       ...
       121, 499,  20, 188,  71, 106, 270, 348, 435, 102],
      dtype='int64', length=350)

In [24]:
c = 0
for i in Training_data_Performance.index:
  c = c + (Training_data_Performance['Actual_y_train'][i] - Training_data_Performance['y_train_pred'][i])**2

print(c / len(Training_data_Performance))

2.239972064726907

In [25]:
from sklearn.metrics import mean_squared_error,r2_score

In [26]:
r2_score(y_train,y_train_pred)

0.9999999812136157

In [27]:
reg.score(X_train,y_train)

0.9999999812136157

In [28]:
mean_squared_error(y_train,y_train_pred)

2.2399720647269072

In [29]:
#Testing_Data_Performance

In [30]:
X_test

     Gender        Age  Annual Salary  Credit Card Debt    Net Worth
361       0  36.126918    74420.10254      10274.135580  551344.3365
73        1  47.789729    59139.21080       4630.544424  473845.8546
374       1  57.134576    67752.38329      13851.921220  657178.4135
155       0  50.219573    55381.53225       5088.239017   20000.0000
104       0  48.476396    63975.06090      10614.854490  891439.8761
..      ...        ...            ...               ...          ...
266       1  40.362058    53921.33351       9046.181090  515305.4841
23        1  47.022284    52027.63837      11960.853770  688466.0503
222       0  47.450949    61063.35631      12066.265710  509543.0859
261       0  37.722824    49346.40500       5827.820346  479685.9824
426       1  41.931168    55514.99340       8009.719809  394229.8972

[150 rows x 5 columns]

In [31]:
y_test

361    46082.80993
73     45058.89690
374    63079.84329
155    31837.22537
104    60461.24268
          ...
266    37076.82508
23     46635.49432
222    46892.26617
261    31249.98803
426    35784.42411
Name: Car Purchase Amount, Length: 150, dtype: float64

In [32]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_test,y_test)

LinearRegression()

In [33]:
reg.coef_

array([7.07092273e-03, 8.41565037e+02, 5.62326909e-01, 2.45823360e-05,
       2.89826264e-02])

In [34]:
reg.intercept_

-42147.01736499498

In [35]:
7.07092273e-03*0	 +  8.41565037e+02*36.126918+ 5.62326909e-01*74420.10254+ 2.45823360e-05*10274.135580 + 2.89826264e-02*551344.3365 + -42147.01736499498

46084.21943194056

In [36]:
y_test_pred = reg.predict(X_test)
y_test_pred

array([46084.21921321, 45060.13579054, 63081.53642833, 31838.3227407 ,
       60460.45067793, 63137.86976301, 52479.8444311 , 54757.38527068,
       52706.95416786, 47869.04393168, 38187.82908085, 56229.68859279,
       44361.69806066, 39002.87498581, 39977.19837178, 55173.31260704,
       48900.72868065, 17584.58579567, 60527.95781016, 49991.22975561,
       41351.95113285, 52785.91528251, 51731.91370956, 38043.18324326,
       41355.40825896, 38241.51718892, 64146.35106392, 47988.14511576,
       22682.30219401, 52242.91580905, 55167.68825319, 45859.27658651,
       41149.00603657, 57430.45008572, 42926.06244964, 39891.99202627,
       61731.79286349, 30840.66512818, 42210.45424676, 40095.90150449,
       57301.6417922 , 60669.98157131, 47443.17620455, 36638.3119922 ,
       53489.10480359, 44433.85233   , 35320.86689545, 42289.79457817,
       52056.96877366, 47241.41546398, 41904.47420799, 32608.19173203,
       38242.58844015, 41767.61389471, 45207.41815019, 48100.15099756,
       60223.3372242 , 44634.2075016 , 44524.46233108, 38502.68854931,
       64188.63873837, 43599.59292121, 22628.65611595, 55376.78205666,
       41220.32102257, 54819.89858271, 59983.34672256, 34215.87728802,
       42998.33341891, 47969.58693756, 60390.92846009, 28735.44217865,
       59483.69278207, 55544.17015842, 59757.78733299, 22090.74158021,
       41319.96977561, 49391.76153223, 32968.94999135, 61404.84919808,
       42371.91003724, 30395.93286703, 35822.32740007, 43724.58740876,
       50664.43128608, 38951.85316072, 38761.97505015, 30669.43899893,
       39889.40225898, 35913.85175623, 29539.7174792 , 37365.51632793,
       30963.48028523, 41135.60077565, 32207.56582885, 49081.25839366,
       45168.15264685, 50956.83247855, 43897.50386576, 53014.63054769,
       46133.60088722, 29518.12985131, 54828.24716148, 59621.56104711,
       25251.93227398, 47381.09601181, 42321.12898047, 42010.64406276,
       45368.08524466, 39765.75499937, 39412.60340055, 49569.80557488,
       39911.65046907, 44387.2638642 , 52571.078706  , 53021.85250964,
       66162.66321313, 49398.36117783, 41452.89568081, 28031.00577655,
       61119.55262158, 41264.61635702, 52984.25652535, 31300.05540903,
       44431.56892277, 28999.45862551, 39437.03697184, 51684.40405727,
       64391.18876001, 31528.37594422, 44649.4580382 , 51940.57071246,
       69668.73367158, 39550.04103798, 62865.2350365 , 41425.87547068,
       37880.57772368, 45077.35147773, 43904.22957216, 38674.96917923,
       48103.49157017, 32478.37703174, 53112.22150597, 54073.52825272,
       37095.00394896, 37076.83238102, 46635.68954018, 46891.8043775 ,
       31250.70629426, 35784.38387241])

In [37]:
Testing_data_Performance = pd.DataFrame()
Testing_data_Performance = X_test.copy()
Testing_data_Performance['Actual_y_test'] = y_test.copy()
Testing_data_Performance['y_test_pred'] = y_test_pred


Testing_data_Performance

,Gender,Age,Annual Salary,Credit Card Debt,Net Worth,Actual_y_test,y_test_pred
361,0,36.126918,74420.10254,10274.135580,551344.3365,46082.80993,46084.219213
73,1,47.789729,59139.21080,4630.544424,473845.8546,45058.89690,45060.135791
374,1,57.134576,67752.38329,13851.921220,657178.4135,63079.84329,63081.536428
155,0,50.219573,55381.53225,5088.239017,20000.0000,31837.22537,31838.322741
104,0,48.476396,63975.06090,10614.854490,891439.8761,60461.24268,60460.450678
...,...,...,...,...,...,...,...
266,1,40.362058,53921.33351,9046.181090,515305.4841,37076.82508,37076.832381
23,1,47.022284,52027.63837,11960.853770,688466.0503,46635.49432,46635.689540
222,0,47.450949,61063.35631,12066.265710,509543.0859,46892.26617,46891.804378
261,0,37.722824,49346.40500,5827.820346,479685.9824,31249.98803,31250.706294
426,1,41.931168,55514.99340,8009.719809,394229.8972,35784.42411,35784.383872

In [38]:
Testing_data_Performance.index

Index([361,  73, 374, 155, 104, 394, 377, 124,  68, 450,
       ...
        66, 208, 479,  94, 253, 266,  23, 222, 261, 426],
      dtype='int64', length=150)

In [39]:
d = 0
for i in Testing_data_Performance.index:
  d = d + (Testing_data_Performance['Actual_y_test'][i] - Testing_data_Performance['y_test_pred'][i])**2

print(d / len(Testing_data_Performance))

1.9590174036375834

In [40]:
from sklearn.metrics import mean_squared_error,r2_score
r2_score(y_test,y_test_pred)

0.9999999816406447

In [41]:
reg.score(X_test,y_test)

0.9999999816406447

In [42]:
mean_squared_error(y_test,y_test_pred)

1.959017403637584

In [43]:
import numpy as np
import pandas as pd
import sklearn
import sys
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
class TRAINING:
    def __init__(self,location):
        try:
            self.df = pd.read_csv(location)
            self.X = self.df.iloc[: , :-1] # independent
            self.y = self.df.iloc[: , -1] # dependent
            self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(self.X,self.y,test_size=0.3,random_state=42)
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def data_training(self):
        try:
            self.reg = LinearRegression()
            self.reg.fit(self.X_train,self.y_train) # trainnig
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def train_performance(self):
        try:
            self.y_train_pred = self.reg.predict(self.X_train)
            print(f' Train Accuracy : -> {r2_score(self.y_train,self.y_train_pred)}')
            print(f'Train Loss : {mean_squared_error(self.y_train,self.y_train_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')
    def testing(self):
        try:
            self.y_test_pred = self.reg.predict(self.X_test)
            print(f' Test Accuracy : -> {r2_score(self.y_test, self.y_test_pred)}')
            print(f'Test Loss : {mean_squared_error(self.y_test,self.y_test_pred)}')
        except Exception as e:
            error_type, error_msg, err_line = sys.exc_info()
            print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

if __name__ == "__main__":
    try:
        obj = TRAINING('Car_Purchasing_Data.csv') # constructor will be called
        obj.data_training()
        obj.train_performance()
        obj.testing()
    except Exception as e:
        error_type,error_msg,err_line = sys.exc_info()
        print(f'Error from Line {err_line.tblineno} -> type {error_type} -> Error msg -> {error_msg}')

 Train Accuracy : -> 0.9999999812136157
Train Loss : 2.2399720647269072
 Test Accuracy : -> 0.9999999808814803
Test Loss : 2.0400233206749734